HTTPS proxy

diff --git a/bin/configure b/bin/configure
--- a/bin/configure
+++ b/bin/configure
@@ -1,26 +1,94 @@
 #!/bin/sh
 
-PID_FILE=/tmp/tinyproxy.pid
-PORT=65050
-BASIC_AUTH=''
-ALLOW=''
+mkdir -p /foxhole/letsencrypt
 
 echo
-echo '1/2 Configure authentication'
-read -p '    Username: ' USERNAME
+if [[ "$(read -p '1/3 Enable HTTPS (requires a registered domain name)? [y/n] ' YES && echo $YES)" == [yY] ]]; then
+    read -p '    Domain name: ' DOMAIN_NAME
 
-[ "$USERNAME" ] && read -p '    Password: ' PASSWORD
+    if [ "$DOMAIN_NAME" ]; then
 
-[ "$PASSWORD" ] && BASIC_AUTH="BasicAuth ${USERNAME} ${PASSWORD}"
+        CERT_DIR="/etc/letsencrypt/live/$DOMAIN_NAME"
 
-[ "$BASIC_AUTH" ] || echo '    Authentication disabled'
+        if [ -d "$CERT_DIR" ] && [[ "$(read -p '    Certificates already exist. Overwrite? [y/n] ' YES && echo $YES)" == [yY] ]]; then
+            echo 'DELETE CERTS'
+#            rm -rf "$CERT_DIR"
+        fi
+
+        if ! [ -d "$CERT_DIR" ]; then
+            echo
+            echo 'Obtaining a certificate...'
+
+#            echo
+#            echo "server { listen 80; }" > /etc/nginx/conf.d/default.conf
+#
+#            echo
+#            certbot certonly \
+#                --nginx \
+#                --non-interactive \
+#                --agree-tos \
+#                --no-eff-email \
+#                --no-redirect \
+#                --email "admin@$DOMAIN_NAME" \
+#                --cert-name "$DOMAIN_NAME" \
+#                --domain "$DOMAIN_NAME"
+        fi
+
+        ln -snf "$CERT_DIR" /etc/letsencrypt/live/foxhole
+
+        cp -f /etc/nginx/foxhole.conf /etc/nginx/conf.d/default.conf
+
+        [ -f /var/run/nginx.pid ] && nginx -s reload
+    else
+        echo
+        echo 'HTTPS configuration aborted'
+    fi
+else
+    rm -f /etc/letsencrypt/live/foxhole
+fi
+
+PROXY_PID_FILE=/tmp/tinyproxy.pid
+PROXY_BASIC_AUTH=''
+PROXY_ALLOW=''
+
+if [ -L /etc/letsencrypt/live/foxhole ]; then
+    DOMAIN_NAME="$(basename "$(readlink -f /etc/letsencrypt/live/foxhole)")"
+    PROXY_LISTEN=127.0.0.1
+    PROXY_PORT=8080
+    PUBLIC_PORT=443
+else
+    PROXY_LISTEN=0.0.0.0
+    PROXY_PORT=80
+    PUBLIC_PORT=80
+fi
 
 echo
-if [[ "$(read -p '2/2 Enable IP whitelist? [y/n]: ' YES && echo $YES)" == [yY] ]]; then
+if [[ "$(read -p '2/3 Configure users? [y/n] ' YES && echo $YES)" == [yY] ]]; then
+    while true; do
+        read -p '    Username: ' USERNAME
+
+        [ "$USERNAME" ] && read -p '    Password: ' PASSWORD
+
+        [ -z "$PASSWORD" ] && break
+
+        PROXY_BASIC_AUTH=$(echo -e "${PROXY_BASIC_AUTH}\nBasicAuth ${USERNAME} ${PASSWORD}")
+
+        echo
+        ! [[ "$(read -p '    Add another user? [y/n] ' YES && echo $YES)" == [yY] ]] && break
+    done
+fi
+
+echo
+if [[ "$(read -p '3/3 Enable IP whitelist? [y/n] ' YES && echo $YES)" == [yY] ]]; then
     while true; do
         read -p '    Enter an IP address: ' IP
+
         [ -z "$IP" ] && break
-        ALLOW=$(echo -e "${ALLOW}\nAllow ${IP}")
+
+        PROXY_ALLOW=$(echo -e "${PROXY_ALLOW}\nAllow ${IP}")
+
+        echo
+        ! [[ "$(read -p '    Add another IP? [y/n] ' YES && echo $YES)" == [yY] ]] && break
     done
 fi
 
@@ -29,24 +97,32 @@ mkdir -p /etc/tinyproxy
 cat >/etc/tinyproxy/tinyproxy.conf <<EOF
 User nobody
 Group nogroup
-PidFile "${PID_FILE}"
-Port ${PORT}
-Listen 0.0.0.0
+PidFile "${PROXY_PID_FILE}"
+Listen ${PROXY_LISTEN}
+Port ${PROXY_PORT}
 Timeout 600
 MaxClients 256
 DisableViaHeader Yes
-${BASIC_AUTH}
-${ALLOW}
+LogLevel Info
+${PROXY_BASIC_AUTH}
+${PROXY_ALLOW}
 EOF
 
 echo
 echo 'Starting server...'
 
-while [ ! -f "$PID_FILE" ]; do
+echo
+cat /etc/tinyproxy/tinyproxy.conf
+
+while [ ! -f "$PROXY_PID_FILE" ]; do
     sleep 2
 done
 
-PUBLIC_IP_ADDR=$(wget -qO- http://myip.enix.org/REMOTE_ADDR)
+if [ "$DOMAIN_NAME" ]; then
+    PUBLIC_ADDR="$DOMAIN_NAME"
+else
+    PUBLIC_ADDR=$(wget -qO- http://myip.enix.org/REMOTE_ADDR)
+fi
 
 echo
-echo -e "Server started successfully: \033[0;32m${PUBLIC_IP_ADDR}:${PORT}\033[0m"
+echo -e "Server started successfully: \033[0;32m${PUBLIC_ADDR}:${PUBLIC_PORT}\033[0m"
